### PR TITLE
Add Password type and validator along with tests.

### PR DESCRIPTION
**Pull request by nickescobedo**
In regards to #1 I've added a Password type and validator.

Hope this helps! 😄

### CODE REVIEW

**Comment by 2DSharp** [comment]
Thanks for the PR, this looks good as I skimmed through. I will get back to it in a minute.

**Comment by 2DSharp** [comment]
Hi, 

The password validation approach is nice, but the concrete definition of what a valid password looks like in the validator seems not very flexible. Different websites might have different notions about valid passwords, completely depending on their business rules. Maybe we could enforce these rules in the `options` array (for example: `min_chars = 8`, `upper_case = 1` etc.)?

Just an idea, although this option could also be directly implemented with custom validators as well. Would like to know what you think.

Edit: I confused myself while writing that comment. Turns out, the only way to enforce custom rules would be by using a custom validator.

**Comment by nickescobedo** [comment]
You have good points.

8 character minimum should be in the default validator.
I will add this.

The default password validator in my opinion wouldn't have options.
If someone wants something custom they should create their own validator.

Thoughts?

**Comment by 2DSharp** [comment]
8 minimum characters in a password seems like a reasonable requirement. And I agree with the custom validator for custom requirements.

Also, I would like to add, the error messages being output would depend on different kinds of validation failures. How about letting the validator trigger an error message based on which condition fails? 

See: https://github.com/2DSharp/Phypes/issues/7

**Comment by 2DSharp** [comment]
@nickescobedo I would like to know your thoughts on implementing https://github.com/2DSharp/Phypes/issues/7

**Review by 2DSharp — APPROVED** [review]
Seems good to go for now. Would need to separate those tiny validations to separate functions in the future.

**Comment by nickescobedo** [comment]
Yes, that is reasonable. The exception message probably doesn't make sense to the user anyways. While I was adding the minimum character count and looking at the tests I was thinking the same thing.

#7 should probably be a separate pull request though. Adding a getMessage or something similar on the interface will break all types so would probably be best in a separate PR.

**Comment by 2DSharp** [comment]
Yea, I am working on that idea on a separate branch, merging this one and the others that follow the current methodology first. Thanks!

**Comment by nickescobedo** [comment]
👍

**Pull request merged**
